# -*- coding: utf-8 -*-
{
    'name': "Consolidation Odoo Community",
    'category': 'Accounting/Accounting',
    'sequence': 206,
    'summary': """All you need to make financial consolidation""",
    'description': """All you need to make financial consolidation""",
    'depends': ['base','account'],
    'author': "Weodu.com",
    'website': "https://apps.weodu.com",
    'version':  "17.0.0.1",
    'price': 240,
    'data': [
        'security/account_consolidation_security.xml',
        'security/ir.model.access.csv',
        'data/consolidated_balance_report.xml',
        'data/account_report_actions.xml',
        'data/onboarding_data.xml',
        'data/pdf_export_templates.xml',
        'views/report_template.xml',
        'views/account_account_views.xml',
        'views/account_move_views.xml',
        'views/consolidation_account_views.xml',
        'views/consolidation_journal_views.xml',
        'views/consolidation_period_views.xml',
        'views/consolidation_account_group_views.xml',
        'views/consolidation_chart_views.xml',
        'views/consolidation_rate_views.xml',
        'views/menuitems.xml',
    ],
    'installable': True,
    'application': True,
    'assets': {
        'wdu_account_consolidation.assets_pdf_export': [
            ('include', 'web._assets_helpers'),
            'web/static/src/scss/pre_variables.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            ('include', 'web._assets_bootstrap_backend'),
            'web/static/fonts/fonts.scss',
            'wdu_account_consolidation/static/src/scss/**/*',
        ],
        'web.report_assets_common': [
            'wdu_account_consolidation/static/src/scss/account_pdf_export_template.scss',
        ],
        'web.assets_backend': [
            'wdu_account_consolidation/static/src/scss/consolidation_kanban.scss',
            'wdu_account_consolidation/static/src/components/**/*',
            'wdu_account_consolidation/static/src/js/**/*',
        ],
    },
    'license': 'AGPL-3',
}
